"""Create table birds

Revision ID: c93a14d1aa19
Revises: 1cff9a605dcf
Create Date: 2022-10-21 11:05:23.587383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.#1cff9a605dcf old: 2739c2b577b9
revision = 'c93a14d1aa19'
down_revision = '1cff9a605dcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
